# Generated by Django 5.0.3 on 2024-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('department', models.CharField(choices=[('General', 'General'), ('Ortho', 'Ortho'), ('Neuro', 'Neuro')], max_length=50)),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('doctor_details', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
