# Generated by Django 5.0.3 on 2024-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('Delux', 'Delux')], max_length=100)),
                ('available_beds', models.IntegerField(default=0)),
            ],
        ),
    ]
